name: Update Latest NSE holidays
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 15 * * 6'
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Updated Latest holidays in csv File
      CI_COMMIT_AUTHOR: shikharvaish28
    steps:
      - uses: actions/checkout@v3
      # Build steps
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python holidays.py

      # Commit and push all changed files.
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: contains(fromJson('["schedule", "pull_request"]'), github.event_name) || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "shikharvaish28@users.noreply.github.com"
          git add --all
          git commit --all -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
